---
abstract: 'script which notifies you what xmms2 is playing'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-XMMS2-Notifier
no_index:
  directory:
    - t
    - inc
requires:
  Audio::XMMSClient: '0.03'
  Getopt::Long: '0'
  Gtk2::Notify: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=app-xmms2-notifier.git
version: '0.001001'
